version: '3'
services:
    postgres:
        image: postgres
        ports:
            - "5432"
        environment:
            - POSTGRES_PASSWORD=postgres
    server:
        build: ./server
        command: gin
        volumes:
            - . :/go/src/go-major-assignment
        ports:
            - "4000:3000"